### ISSUE TITLE
Doesn't work with ../ paths

### ISSUE THREAD

**Issue by silvenon** [disqus/grunt-smartrev#5]
**EDIT**: This is the whole project:

```
├── Gruntfile.coffee
├── images
│   └── avatar.png
├── index.html
├── package.json
├── stats.json
└── styles
    └── main.css
```

`Gruntfile.coffee`:

``` coffee
module.exports = (grunt) ->

  grunt.initConfig

    smartrev:
      options:
        cwd: './'
        noRename: ['index.html']
      dist:
        src: [
          'index.html'
          'styles/*.css'
          'images/*.*'
        ]
        dest: 'stats.json'

  grunt.loadNpmTasks('grunt-smartrev')

  grunt.registerTask 'default', ['smartrev']
```

`index.html`:

``` html
<!doctype html>
<html>
  <head>
    <title>Smartrev test</title>
    <link rel="stylesheet" href="styles/main.css" />
  </head>

  <body>
  </body>
</html>
```

`styles/main.css`:

``` css
html,
body {
  height: 100%;
}

body {
  background-image: url(../images/avatar.png);
}
```

`stats.json`:

``` json
{"index.html":{"newName":"index.html","height":2,"size":189,"dependencies":["styles/main.css"]},"styles/main.css":{"newName":"styles/main.b05dc4e215a0496ee7ba6242920f2563.css","height":1,"size":116,"dependencies":["images/woman.jpg"]},"images/woman.jpg":{"newName":"images/woman.e5f4fd5b0ae7f68af14a8e91ce7b7ec7.jpg","height":0,"size":100293,"dependencies":[]}}
```

When I run `grunt`, `images/avatar.png` and `styles/main.css` get properly revved, but this is what I find in `styles/main.css`:

``` css
body {
  background-image: url(images/avatar.e5f4fd5b0ae7f68af14a8e91ce7b7ec7.png);
}
```
